# Generated by Django 4.0.6 on 2022-07-05 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_subscribers_category_subscribe_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscribers',
            old_name='categoryID',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='subscribers',
            old_name='userID',
            new_name='user',
        ),
    ]
