# Generated by Django 4.0.6 on 2022-07-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_categoryid_subscribers_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='datetime_of_topic',
        ),
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
